# Generated by Django 4.2.6 on 2023-10-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='priority',
            new_name='pri',
        ),
    ]
