# Generated by Django 4.2.6 on 2023-10-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_task_tasks_rename_priority_tasks_pri'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='2023-05-23'),
            preserve_default=False,
        ),
    ]
